[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm", "openssl"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["npx prisma generate", "pnpm build"]

[start]
cmd = "node dist/index.js"
